# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Krlxe1DlBmyg6pQPyp7YYFytCaOsagN_
"""

# Answer: Django signals run in the same thread as the caller.

import threading
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

@receiver(post_save, sender=User)
def check_thread(sender, instance, **kwargs):
    print(f"Signal thread ID: {threading.get_ident()}")

print(f"Caller thread ID: {threading.get_ident()}")
User.objects.create(username="threadcheck")