# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTK4u54_1bmEj3suD4qWzNEEED4Wsx3_
"""

# Answer: This class supports iteration to return length and width.

class Rectangle:
    def __init__(self, length: int, width: int):
        self.length = length
        self.width = width
        self._index = 0

    def __iter__(self):
        self._index = 0
        return self

    def __next__(self):
        if self._index == 0:
            self._index += 1
            return {"length": self.length}
        elif self._index == 1:
            self._index += 1
            return {"width": self.width}
        else:
            raise StopIteration

r = Rectangle(10, 5)
for val in r:
    print(val)